name: Django Testing and Deploy

# Указываем при каких условиях срабатывает workflow
on:
  push:
    branches: [master]

#
jobs:
  tests:
    runs-on: ubuntu-latest
    env:
      DB_USER: admin
      DB_PASS: adminpass
      DB_HOST: localhost
      DB: stocks
      SECRET_KEY: django-insecure-nw^y+m^wmxza1asgk+)!ua2qx9)g+#v=6%76-9i8i(6eqiw94j
      ALLOWED_HOSTS: '*'
    services:
      postgres_main:
        image: postgres
        env:
          POSTGRES_USER: ${{ env.DB_USER }}
          POSTGRES_PASSWORD: ${{ env.DB_PASS }}
          POSTGRES_DB: ${{ env.DB }}
        ports:
          - 5432:5432
        options:
          --health-cmd pg_isready
          --health-interval 5s
          --health-timeout 5s
          --health-retries 5
    steps:
      - name: Checking for Changes
        uses: actions/checkout@v2

      - name: Installation Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.11.0

      - name: Installation requirements
        run: pip install -r requirements.txt

#      - name: Code linting
#        run: flake8 logistic

#      - name: Testing
#        run: pytest
#        env:
#          SECRET_KEY: ${{ env.SECRET_KEY }}
#          DEBUG: "0"
#          DB_ENGINE: django.db.backends.postgresql
#          DB_NAME: ${{ env.DB }}
#          DB_USER: ${{ env.DB_USER }}
#          DB_PASSWORD: ${{ env.DB_PASS }}
#          DB_HOST: ${{ env.DB_HOST }}
